apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-deployment
spec:
  selector:
    matchLabels:
      app: identity
  template:
    metadata:
      labels:
        app: identity
    spec:
      containers:
      - name: identity
        image: playeconomyacrdev.azurecr.io/play.identity
        env:
          - name: ServiceSettings__MessageBroker
            value: SERVICEBUS
          - name: MongoDbSettings__ConnectionString
            valueFrom: 
              secretKeyRef:
                key: cosmosdb-connectionstring
                name: identity-secrets
          - name: ServiceBusSettings__ConnectionString
            valueFrom: 
              secretKeyRef:
                key: servicebusconnectionstring
                name: identity-secrets
          - name: IdentitySettings__AdminUserPassword
            valueFrom: 
              secretKeyRef:
                key: admin-password
                name: identity-secrets
        resources:
          limits:
            memory: "128Mi"
            cpu: "150m"
        ports:
        - containerPort: 5002
