microserviceName: "identity"

image:
  repository: playeconomyacrdev.azurecr.io/play.identity
  tag: 1.0.10

envVariables:
  IdentitySettings__PathBase: /identity-svc
  IdentitySettings__CertificateCerFilePath: /certificates/certificate.crt
  IdentitySettings__CertificateKeyFilePath: /certificates/certificate.key
  IdentityServerSettings__Clients__1__RedirectUris__0: "https://playeconomy.southindia.cloudapp.azure.com/authentication/login-callback"
  IdentityServerSettings__Clients__1__PostLogoutRedirectUris__0: "https://playeconomy.southindia.cloudapp.azure.com/authentication/logout-callback"

resources:
  limits:
    memory: "256Mi"
    cpu: "300m"

container:
  port: 5002
  volumeMounts:
    - name: certificate-volume
      mountPath: /certificates

volumes:
  - name: certificate-volume
    secret:
      secretName: signing-cert
      items:
        - key: tls.key
          path: certificate.key
        - key: tls.crt
          path: certificate.crt

certificate:
  secretName: signing-cert
  hostName: playeconomy.southindia.cloudapp.azure.com

identityClientId: e52507c0-8aad-4359-bfd1-f1548f7a1682